### ISSUE TITLE
I'm getting the following error

### ISSUE THREAD

**Issue by likhitha224** [Abhay0899193/Speaker-Recognition#4]
![Screenshot (91)](https://user-images.githubusercontent.com/60059750/72677716-65da6000-3ac5-11ea-89d4-7d81290fc960.png)

**Comment by likhitha224** [comment]
if the image is not visible,the following is the error i got:

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python36\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Python36\Speaker-Recognition\train.py", line 120, in train
    traine(v1.get())
  File "C:\Python36\Speaker-Recognition\GMM1.py", line 45, in traine
    gmm = GMM(n_components = 16, n_iter = 200, covariance_type='diag',n_init = 10)
TypeError: __init__() got an unexpected keyword argument 'n_iter'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python36\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Python36\Speaker-Recognition\test.py", line 62, in testaudio
    k = test1()
  File "C:\Python36\Speaker-Recognition\username.py", line 62, in test1
    models    = [pickle.load(open(fname,'rb')) for fname in gmm_files]
  File "C:\Python36\Speaker-Recognition\username.py", line 62, in <listcomp>
    models    = [pickle.load(open(fname,'rb')) for fname in gmm_files]
ModuleNotFoundError: No module named 'sklearn.mixture.gmm'
